theme: jekyll-theme-cayman
SEOTitle: 客家野夫的博客 | kejiayefu
email: wiyalee@gmail.com
description: "客家野夫的博客"
keyword: "客家野夫，kejiayefu，客家野夫的博客，技术博客，人，技术，生活。"
url: "https://kejiayefu.github.io"
github_username: kejiayefu
